# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_commented', models.DateField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
