# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Maximum 100 letters', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_bookmarked',
            field=models.BooleanField(default=False, verbose_name='Is favourite?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Maximum 200 letters', max_length=200),
        ),
    ]
