# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161009_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
